name: todo_app
description: "A todo_app to showcase understanding of Riverpod."

publish_to: 'none' 


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
